
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\AGH\SEMESTR_6\Elektroniczna aparatura medyczna\Ćwiczenia projektowe\sygnały eam\sygnały eam\na_stole_5kg_iza.ASC
%
% Auto-generated by MATLAB on 06-May-2022 16:12:00


%% Setup the Import Options and import the data
clear all;
close all;

opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [32, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["MegaWinASCIIfile", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "MegaWinASCIIfile", "TrimNonNumeric", true);
opts = setvaropts(opts, "MegaWinASCIIfile", "ThousandsSeparator", ",");

% Import the data
pompki_damskie = readtable("C:\Users\Asus\Desktop\semestr 6\EAM\projekt\eam\Iza\pompki_damskie_iza.ASC", opts);
pompki_meskie = readtable("C:\Users\Asus\Desktop\semestr 6\EAM\projekt\eam\Iza\pompki_meskie_iza.ASC", opts);

%% Convert to output type
pompki_damskie = table2array(pompki_damskie);
pompki_meskie = table2array(pompki_meskie);
%% Take only second column
pompki_damskie = pompki_damskie(:,2);
pompki_meskie = pompki_meskie(:,2);
%% Clear temporary variables
clear opts
%% OBRÓBKA DANYCH
%% Zero crossing    
time = (1:1:10)

pompki_damskie_cross = pompki_damskie(1:10000,:);
pompki_meskie_cross = pompki_meskie(1:10000,:);

first_divide_damskie = buffer(pompki_damskie_cross, numel(pompki_damskie_cross)/10); 
counter_damskie = zeros(10,1)
first_divide_meskie = buffer(pompki_meskie_cross, numel(pompki_meskie_cross)/10); 
counter_meskie = zeros(10,1)

for i = 1:10
    for j = 1:999
        if first_divide_damskie(j, i) * first_divide_damskie(j+1, i) < 0
            counter_damskie(i) = counter_damskie(i) + 1;
        end
    end
end

for i = 1:10
    for j = 1:999
        if first_divide_meskie(j, i) * first_divide_meskie(j+1, i) < 0
            counter_meskie(i) = counter_meskie(i) + 1;
        end
    end
end

figure()
subplot(1, 2, 1)
plot(pompki_damskie_cross)
title('Surowy sygnał EMG')
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
subplot(1, 2, 2)
bar(time, counter_damskie)
title('Częstość występowania amplitudy równej 0 - pompki damskie')
xlabel('Czas [s]')
ylabel('Ilość przekroczeń zer')
grid on;

figure()
subplot(1, 2, 1)
plot(pompki_meskie_cross)
title('Surowy sygnał EMG')
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
subplot(1, 2, 2)
bar(time, counter_meskie)
title('Częstość występowania amplitudy równej 0 - pompki meskie')
xlabel('Czas [s]')
ylabel('Ilość przekroczeń zer')
grid on;


%% Fourier Transform
L_lo = length(pompki_damskie);
L_hi = length(pompki_meskie);

fs = 1000; %sampling frequency
f_lo = fs*(0:(L_lo/2))/L_lo; % FFT frequency from 0 to L/2 data length
f_hi = fs*(0:(L_hi/2))/L_hi;

%compute two sided spectrum (-Fmax:Fmax)
p1 = fft(pompki_damskie);
p2 = fft(pompki_meskie);

%divive by L for normalization of the power of the output 
p1 = abs(p1/L_lo);
p2 = abs(p2/L_hi);

% compute signal sided spectrum
p1=p1(1:L_lo/2+1);
p1(2:end-1) = 2*p1(2:end-1);
p2=p2(1:L_hi/2+1);
p2(2:end-1) = 2*p2(2:end-1);

%Plotting FFT
figure()
subplot(1, 2, 1)
plot(f_lo, p1)
xlabel('Frequency[Hz]')
ylabel('Intensity')
title('FFT (pompki damskie)')
grid on;
ylim([0 10])

subplot(1, 2, 2)
plot(f_hi, p2)
xlabel('Frequency[Hz]')
ylabel('Intensity')
title('FFT (pompki męskie)')
grid on;
ylim([0 10])
%% Rectification
pompki_damskie = abs(pompki_damskie);
pompki_meskie = abs(pompki_meskie);
%% RMS Mean Power of signal
envelope_lo = zeros(L_lo, 1);
envelope_hi = zeros(L_hi, 1);
window = 100;
envelope_lo = sqrt(movmean(pompki_damskie.^2, window));
envelope_hi = sqrt(movmean(pompki_meskie.^2, window));
%% Normalization with MVC
MVC_lo = max(pompki_damskie);
MVC_lo_normalised = zeros(L_lo, 1);
MVC_lo_normalised = envelope_lo./MVC_lo.*100;

MVC_hi = max(pompki_meskie);
MVC_hi_normalised = zeros(L_hi, 1);
MVC_hi_normalised = envelope_hi./MVC_hi.*100;

figure()
plot(pompki_damskie)
hold on;
plot(envelope_lo, 'r')
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
xlim([0 30000])
title('Normalizacja MVC (pompki damskie)')
legend('EMG signal', 'Normalized signal')

figure()
plot(pompki_meskie)
hold on;
plot(envelope_hi, 'r')
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
xlim([0 25000])
title('Normalizacja MVC (pompki męskie)')
legend('EMG signal', 'Normalized signal')

%% POMPKI DAMKSIE 
figure()

subplot(3,1,1)
plot(pompki_damskie,"b")
hold on
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki damksie")
legend("sygnał wyjściowy")
xlim([0 25000])

subplot(3,1,2)
pompki_damskie = abs((pompki_damskie));
plot(pompki_damskie,"b")
hold on
%M2 = movmean(pompki_damskie,200);
M1 = conv2(pompki_damskie, ones(101,1)/101, 'same');
plot(M1,"g")
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki damksie")
legend("moduł z sygnału", "filtracja movingAverage")
xlim([0 25000])

subplot(3,1,3)
plot(M1,"g")
legend("filtracja movingAverage")
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki damksie")
xlim([0 25000])

%% POMPKI MĘSKIE

figure()

subplot(3,1,1)
plot(pompki_meskie,"b")
hold on
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki męskie")
legend("sygnał wyjściowy")
xlim([0 25000])

subplot(3,1,2)
pompki_meskie = abs((pompki_meskie));
plot(pompki_meskie,"b")
hold on
%M2 = movmean(pompki_meskie,200);
M2 = conv2(pompki_meskie, ones(101,1)/101, 'same');
plot(M2,"g")
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki męskie")
legend("moduł z sygnału", "filtracja movingAverage")
xlim([0 25000])

subplot(3,1,3)
plot(M2,"g")
legend("filtracja movingAverage")
xlabel("Time [ms]")
ylabel("Amplitude [μV]")
title("Pompki męskie")
xlim([0 25000])

%% Dopasowanie krzywej do sygnałów movingAverage

t1 = linspace(0,30000, length(M1));
% M1 = M1(:,2);

t2 = linspace(0,30000, length(M2));
% M2 = M2(:,2);

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t1, M1 );

% Set up fittype and options.
ft = fittype( 'sin5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [110.849335472377 0.00010471975511966 0.0298195712314237 43.8180520448842 0.00020943951023932 1.74994800471903 33.1913573588532 0.00251327412287183 -0.618865102560703 29.174914717248 0.00272271363311115 2.00746009302972 20.1716972451895 0.00293215314335047 1.52172179629481];

% Fit model to data.
[fitresult1, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult1);
legend( h, 'M1 vs. t1', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't1', 'Interpreter', 'none' );
ylabel( 'M1', 'Interpreter', 'none' );
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( t2, M2 );

% Set up fittype and options.
ft = fittype( 'sin5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [136.076210958716 0.00010471975511966 0.023051679088262 40.4136528218724 0.000837758040957278 -1.76193910383351 48.8255145501885 0.00020943951023932 1.69888946046219 33.455203446977 0.0010471975511966 1.70503197011569 16.7960620618971 0.000418879020478639 2.08360027305135];

% Fit model to data.
[fitresult2, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 6' );
h = plot( fitresult2);
legend( h, 'M2 vs. t2', 'untitled fit 6', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't2', 'Interpreter', 'none' );
ylabel( 'M2', 'Interpreter', 'none' );
grid on

%% 

plot( fitresult1, "r")
hold on
plot( fitresult2, "b")
legend("Pompki damskie", "Pompki męskie")
xlabel("Time [ms]")
ylabel("Amplitude [μV]")

grid on
hold off
